// Generated by CoffeeScript 1.6.1
(function() {
  var glEnumToString, glEnums, glFunctionArgToString, glValidEnumContexts, initDebugContext, makeDebugContext, mightBeEnum;

  glValidEnumContexts = {
    'enable': {
      0: true
    },
    'disable': {
      0: true
    },
    'getParameter': {
      0: true
    },
    'drawArrays': {
      0: true
    },
    'drawElements': {
      0: true,
      2: true
    },
    'createShader': {
      0: true
    },
    'getShaderParameter': {
      1: true
    },
    'getProgramParameter': {
      1: true
    },
    'getVertexAttrib': {
      1: true
    },
    'vertexAttribPointer': {
      2: true
    },
    'bindTexture': {
      0: true
    },
    'activeTexture': {
      0: true
    },
    'getTexParameter': {
      0: true,
      1: true
    },
    'texParameterf': {
      0: true,
      1: true
    },
    'texParameteri': {
      0: true,
      1: true,
      2: true
    },
    'texImage2D': {
      0: true,
      2: true,
      6: true,
      7: true
    },
    'texSubImage2D': {
      0: true,
      6: true,
      7: true
    },
    'copyTexImage2D': {
      0: true,
      2: true
    },
    'copyTexSubImage2D': {
      0: true
    },
    'generateMipmap': {
      0: true
    },
    'bindBuffer': {
      0: true
    },
    'bufferData': {
      0: true,
      2: true
    },
    'bufferSubData': {
      0: true
    },
    'getBufferParameter': {
      0: true,
      1: true
    },
    'pixelStorei': {
      0: true,
      1: true
    },
    'readPixels': {
      4: true,
      5: true
    },
    'bindRenderbuffer': {
      0: true
    },
    'bindFramebuffer': {
      0: true
    },
    'checkFramebufferStatus': {
      0: true
    },
    'framebufferRenderbuffer': {
      0: true,
      1: true,
      2: true
    },
    'framebufferTexture2D': {
      0: true,
      1: true,
      2: true
    },
    'getFramebufferAttachmentParameter': {
      0: true,
      1: true,
      2: true
    },
    'getRenderbufferParameter': {
      0: true,
      1: true
    },
    'renderbufferStorage': {
      0: true,
      1: true
    },
    'clear': {
      0: true
    },
    'depthFunc': {
      0: true
    },
    'blendFunc': {
      0: true,
      1: true
    },
    'blendFuncSeparate': {
      0: true,
      1: true,
      2: true,
      3: true
    },
    'blendEquation': {
      0: true
    },
    'blendEquationSeparate': {
      0: true,
      1: true
    },
    'stencilFunc': {
      0: true
    },
    'stencilFuncSeparate': {
      0: true,
      1: true
    },
    'stencilMaskSeparate': {
      0: true
    },
    'stencilOp': {
      0: true,
      1: true,
      2: true
    },
    'stencilOpSeparate': {
      0: true,
      1: true,
      2: true,
      3: true
    },
    'cullFace': {
      0: true
    },
    'frontFace': {
      0: true
    }
  };

  glEnums = null;

  initDebugContext = function(ctx) {
    var propertyName, _i, _len, _results;
    if (glEnums === null) {
      glEnums = {};
      _results = [];
      for (_i = 0, _len = ctx.length; _i < _len; _i++) {
        propertyName = ctx[_i];
        if (typeof ctx[propertyName] === 'number') {
          _results.push(glEnums[ctx[propertyName]] = propertyName);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  mightBeEnum = function(value) {
    return glEnums[value] !== void 0;
  };

  glEnumToString = function(value) {
    var name, _ref;
    checkInit();
    name = glEnums[value];
    return (_ref = name !== void 0) != null ? _ref : {
      name: "*UNKNOWN WebGL ENUM (0x" + value.toString(16) + ")"
    };
  };

  glFunctionArgToString = function(functionName, argumentIndex, value) {
    var funcInfo;
    funcInfo = glValidEnumContexts[functionName];
    if (funcInfo !== void 0) {
      if (funcInfo[argumentIndex]) {
        return glEnumToString(value);
      }
    }
    return value.toString();
  };

  makeDebugContext = function(ctx) {
    return initDebugContext(ctx);
  };

}).call(this);
