// Generated by CoffeeScript 1.6.1

/* ABOUT
                       __  .__              ________ 
   ______ ____   _____/  |_|__| ____   ____/   __   \
  /  ___// __ \_/ ___\   __\  |/  _ \ /    \____    /
  \___ \\  ___/\  \___|  | |  (  <_> )   |  \ /    / 
 /____  >\___  >\___  >__| |__|\____/|___|  //____/  .co.uk
      \/     \/     \/                    \/         
                                              CoffeeGL
                                              Benjamin Blundell - ben@section9.co.uk
                                              http://www.section9.co.uk

This software is released under the MIT Licence. See LICENCE.txt for details


Error Handling code

- TODO 
  * Line numbers maybe?
  * Problem with using @ as we are including this file in many places with node :S
*/


(function() {
  var CoffeeGLDebug, CoffeeGLError, CoffeeGLLog, CoffeeGLWarning, CoffeeGLWarningOnce, cache,
    _this = this,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  cache = [];

  /* CoffeeGLError
  */


  CoffeeGLError = function(msg, obj) {
    var f;
    f = "CoffeeGL Error : " + msg;
    if (obj != null) {
      f += " in " + obj;
    }
    console.error(f);
    throw f;
  };

  /* CoffeeGLWarning
  */


  CoffeeGLWarning = function(msg, obj) {
    var f;
    f = "CoffeeGL Warning : " + msg;
    if (obj != null) {
      f += " in " + obj;
    }
    return console.warn(f);
  };

  /* CoffeeGLWarningOnce
  */


  CoffeeGLWarningOnce = function(msg, obj) {
    var f, result;
    result = __indexOf.call(cache, msg) >= 0;
    if (!result) {
      f = "CoffeeGL Warning : " + msg;
      if (obj != null) {
        f += " in " + obj;
      }
      console.warn(f);
      return cache.push(msg);
    }
  };

  /* CoffeeGLDebug
  */


  CoffeeGLDebug = function(msg, obj) {
    var f;
    if (CoffeeGL.Context.debug) {
      f = "CoffeeGL Debug : " + msg;
      if (obj != null) {
        f += " in " + obj;
      }
      return console.log(f);
    }
  };

  /* CoffeeGLLog
  */


  CoffeeGLLog = function(msg, obj) {
    var f;
    f = "CoffeeGL Log : " + msg;
    if (obj != null) {
      f += " in " + obj;
    }
    return console.log(f);
  };

  module.exports = {
    CoffeeGLError: CoffeeGLError,
    CoffeeGLWarning: CoffeeGLWarning,
    CoffeeGLLog: CoffeeGLLog,
    CoffeeGLWarningOnce: CoffeeGLWarningOnce,
    CoffeeGLDebug: CoffeeGLDebug
  };

}).call(this);
