// Generated by CoffeeScript 1.6.1
(function() {
  var util;

  util = {};

  util.extend = function(obj, source) {
    var i, il, keys, prop, safeHasOwnProperty;
    if (Object.keys) {
      keys = Object.keys(source);
      i = 0;
      il = keys.length;
      while (i < il) {
        prop = keys[i];
        Object.defineProperty(obj, prop, Object.getOwnPropertyDescriptor(source, prop));
        i++;
      }
    } else {
      safeHasOwnProperty = {}.hasOwnProperty;
      for (prop in source) {
        if (safeHasOwnProperty.call(source, prop)) {
          obj[prop] = source[prop];
        }
      }
    }
    return obj;
  };

  util.removeElement = function(element, list) {
    var index;
    index = list.indexOf(element);
    if (index !== -1) {
      list.splice(index, 1);
    }
    return list;
  };

  util.clone = function(obj) {
    var flags, key, newInstance;
    if ((obj == null) || typeof obj !== 'object') {
      return obj;
    }
    if (obj instanceof Date) {
      return new Date(obj.getTime());
    }
    if (obj instanceof RegExp) {
      flags = '';
      if (obj.global != null) {
        flags += 'g';
      }
      if (obj.ignoreCase != null) {
        flags += 'i';
      }
      if (obj.multiline != null) {
        flags += 'm';
      }
      if (obj.sticky != null) {
        flags += 'y';
      }
      return new RegExp(obj.source, flags);
    }
    if (obj instanceof Float32Array) {
      return new Float32Array(obj);
    }
    if (obj instanceof Uint16Array) {
      return new Uint16Array(obj);
    }
    newInstance = new obj.constructor();
    for (key in obj) {
      newInstance[key] = util.clone(obj[key]);
    }
    return newInstance;
  };

  module.exports = util;

}).call(this);
