version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mvn -s settings.xml dependency:resolve
  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/FoundationsViewer.war
