version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      java: corretto11
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - git submodule update --init docker/db/dl-data-samples
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.... 
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo JAVA_HOME set to $JAVA_HOME
      - mvn -s settings.xml -t toolchains.xml dependency:resolve
  build:
    commands:
      - echo Maven build started on `date`
      - mvn -s settings.xml -t toolchains.xml clean package
      - echo Docker build started on `date`
      - docker build -t $REPOSITORY_URI:$latest -f docker/ui/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build:
    commands:
      - echo Pushing to $REPOSITORY_URI
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`

artifacts:
  files:
    - target/FoundationsViewer.war
