version: "3.7"

services:
  tomcat:
    image: tomcat:9.0.30-jdk11-openjdk
    environment:
      CATALINA_OPTS:
    volumes:
      # Use exploded webapp files, instead of packaged WAR, to allow hot reloading of source JSPs etc.
      - ./src/main/webapp/:/usr/local/tomcat/webapps/ROOT/
      # Classes will be reloaded only if your IDE auto re-compiles, or you run a maven build.
      - ./target/classes/:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/
      - ./target/foundationsviewer-1.0-SNAPSHOT/WEB-INF/lib/:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/

      - ./docker/tomcat-context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
      - ${CUDL_VIEWER_CONFIG:-./docker/cudl-global.properties}:/etc/cudl-viewer/cudl-global.properties
      - ${CUDL_VIEWER_DATA:-../dl-data-samples/processed-data/cudl-data/}:/srv/cudl-viewer/cudl-data/
      - ${CUDL_VIEWER_CONTENT:-../dl-data-samples/processed-data/cudl-viewer-content/}:/srv/cudl-viewer/cudl-viewer-content/
      - ${CUDL_VIEWER_CONTENT_UI:-../dl-data-samples/processed-data/cudl-data/sample.ui.json5}:/srv/cudl-viewer/cudl-data/cudl.ui.json5
    ports:
      - ${CUDL_VIEWER_HOST_PORT:-8888}:8080
    depends_on:
      - cudl-db
  cudl-db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        DBPATH: ${DBPATH:-./docker/db/dl-data-samples/processed-data/database-snapshots}
    restart: always
    environment:
      POSTGRES_USER: cudl
      POSTGRES_DB: cudl
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-password}
    ports:
      - ${CUDL_DB_HOST_PORT:-0}:5432
