<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
	import="ulcambridge.foundations.viewer.model.*"%>
<%
	Collection collection = (Collection) request
			.getAttribute("collection");
%>

<div class="grid_10">
	<h3 style="margin-left: 8px"><%=collection.getTitle()%></h3>
	<blockquote class="grid_5 omega print">

		One may say there is a force like a hundred thousand wedges trying force ‹into› every kind of adapted structure into the gaps ‹of› in the œconomy of Nature, or rather forming gaps by thrusting out weaker ones
		
		<br /> <br />
		
		
		<cite>&mdash;  Charles Darwin<br/>
		Notebook D 135e, 28 September 1838</cite>

	</blockquote>
	<br /> <br />
	<div class="grid_4">
		<img class="collectionOrganisationalImage"
			src="/images/collectionsView/darwin_mss.jpg"
			alt="Japanese Works" width="150" height="225" />
	</div>
	<div class="grid_9">
		<br />
		<p>The <i>Charles Darwin Papers</i> in the Manuscripts Department of Cambridge University Library hold nearly the entire extant collection of Darwin’s working scientific papers. Paramount among these documents are <i>Charles Darwin’s Evolution Manuscripts</i>, which are being published online at the Cambridge Digital Library and simultaneously at the <a href="http://www.amnh.org/our-research/darwin-manuscripts-project">Darwin Manuscripts Project</a> in collaboration with the <a href="http://www.darwinproject.ac.uk/">Darwin Correspondence Project</a>. This is a conceptually coherent set of over 30,000 digitised and edited manuscript pages, spanning 1835-1882. None of these documents have hitherto been digitised to the present high standard of full-colour and high-resolution. While several documents are classics of the Darwin manuscripts corpus, many have never been transcribed and edited before and many that have been published previously are presented here in new and radically improved editions. These documents are organised into two parts, which will be released in two instalments: <i>Creation of the Origin</i> (November 2014) and <i>Darwin’s Evidence</i> (June 2015).</p>

<p><b>Part I Creation of the <i>Origin of Species</i></b> includes the first traces of Darwin’s interest during the <i>Beagle</i> voyage in the species question—broadly defined. It also includes, for contextual purposes, his treatment of those specimens in his own collections and those subjects, such as extinction and biogeography, which he would later revisit in the light of evolution. Beyond these scattered, early theoretical reflections, the bulk of the <i>Creation</i> collection comprises the complete set of theoretical notes and the multiple draft essays that Darwin wrote over a period of two decades (1837-1859). These documents truly constitute the surviving seedbed of the <i>Origin</i>. For in them, Darwin hammered out natural selection and the structure of concepts he used to support natural selection. It was here also that he developed his evolutionary narrative and where he experimented privately with arguments and strategies of presentation that he either rejected or that eventually saw the light of day with the <i>Origin</i>’s publication in 1859.</p>

<p>In the collection, there are several repositories of notes namely: the Transmutation Notebooks and Metaphysical Notebooks of the 1830s. It was in Notebook B, the first Transmutation Notebook, that Darwin first attempted to formulate a full theory of evolution and it was in <a href="/view/MS-DAR-00123">Notebooks D</a> and <a href="/view/MS-DAR-00124">E</a> that natural selection began to take form in late 1838 and early 1839. The further maturation of Darwin’s theory is found in the three experiment notebooks he began in the late 1830s and mid 1850s, and above all in the <i>Origin</i> Portfolios. The latter are a large mass of previously unpublished loose notes, primarily from the 1830s-1850s, which Darwin organised into topics that generally parallel the chapters of the <i>Origin</i>. The <i>Origin</i> Portfolios contain several hundred letters and former enclosures in letters, which Darwin commonly annotated and which he treated as an integral part of the material he gathered for what became the <i>Origin</i>.</p>

<p>Lastly, the <i>Creation</i> collection holds the surviving documentary evidence for the drafting of the <i>Origin</i>, which was a process that scholars have long recognised began not in the 1850s, but in 1842 when Darwin wrote the first in a long chain of draft essays and draft chapters. The first of these was the 35-page document known as the <a href="/view/MS-DAR-00006">1842 Pencil Sketch or the 1842 Essay</a>. Darwin was right to refer to the 1842 document as a ‘sketch’ for it was very rough. But this often crudely schematic document does represent a very first draft of the <i>Origin</i>. Darwin managed to cover much of the over-arching structure, many of the themes, and even some of the most memorable language of the book that he was to publish much expanded, many drafts and many years later. For example, it was in this sketch that Darwin for the first time coined the term Natural Selection, where it appeared as the section head for the two crucial pages of the 1842 Essay that he devoted to the explanatory essence of his theory (<a href="/view/MS-DAR-00006/41">Ms pp. 5 & 6</a>). Darwin began page 5, but quickly crossed-through the short passage he had written. He turned over the page and replaced it with a new page 5.  However, that new start occasioned a historic change and crystallisation of Darwin's scientific language. For, in the first p. 5 he used the circumlocution 'Means of selection', which he then extended to the fairly long phrase '&lt;&lt;Natural&gt;&gt; Means of selection'. But on the new page 5, he began a new section with a new heading, and as far as is known, it was at this moment that Darwin coined a new scientific term: 'Natural Selection'.</p>

<p>The <a href="/view/MS-DAR-00007">1844 Essay</a>, a 189-page draft, was to follow next. Possibly before he launched into writing the 1844 Essay, and definitely during 1844 Essay’s writing, he used the backs of many pages of the 1842 Pencil Sketch to write ink chapter summaries and notes, some with page references to the draft of the 1844 Essay. Darwin also rewrote the opening dozen or so pages of the 1844 draft, but retained the rejected version—published here as <a href="/view/MS-DAR-00006/6">1844 Essay, Part I, Draft A</a>. After he completed writing the 1844 Essay, he had it copied by an amanuensis to produce a <a href="/view/MS-DAR-00113">230 page fair copy</a>, which he may well have intended to publish. If so, Darwin thought better of the idea, but he did revise and annotate the fair copy, which was also critically annotated—with significant impact—by Emma Darwin and Joseph Dalton Hooker, among others.</p>

<p>One set of Darwin’s annotations on the 1844 Essay, namely dark pencil notes on the verso of blank sheets interleaved among the pages of the fair copy, appear to relate to the next phase of Darwin’s writing up the species theory. That is the nine surviving chapters of the very large manuscript (comprising nine thick volumes of the Charles Darwin Papers, DAR 8-16) published posthumously by R. C. Stauffer in 1975 as <i>Charles Darwin’s Natural Selection, Being the second part of his big species book written from 1856 to 1858</i>. While it is true—as we learn from Darwin’s pocket diary (DAR 158)—that he first took pen to foolscap to begin writing <i>Natural Selection</i> in May 1856, we also know from the diary that it was earlier, that is in September 1854, that Darwin actually reengaged with the writing project he had dropped in 1844. He did so not by embarking on a new version of the theory, rather he ‘began sorting notes for species Theory’. This correlates well with the establishment of the <i>Origin</i> Portfolios for his old notes and with a sudden influx of new notes, many datable to November 1854.</p>

<p>The <i>Natural Selection</i> manuscript is the immediate, yet partial, precursor of the <i>Origin</i>. Stauffer refers to it as the ‘second part of his big species book’. The first part, dealing with variation and selection under domestication, was apparently cannibalised either when Darwin wrote Chapters 1 and 2 of the <i>Origin</i> and/or when he wrote <i>Variation under domestication</i> (1868). We know from the Diary that there were two lost, presumably reused, Chapters I and II.  So the <i>Natural Selection</i> manuscript begins with Chapter III and is complete through Chapter X, while Chapter XI is incomplete. The eight surviving full chapters comprising <i>Natural Selection</i> clearly show that the big book was conceived on a larger scale than the <i>Origin</i>. It is characterized by its richness of detail and the fact that it has footnotes and a presumptive bibliography. Darwin hoped that it would be published in 1860. In fact, when he stopped writing in June 1858, he had not that much further to do to complete the book to the draft stage. Judging by the <i>Origin</i>, he had but four topics left to cover. He had to complete geographic distribution, write <i>de novo</i> chapters on palaeontology and on the related topics he grouped together under classification, morphology, embryology, and rudimentary organs, and he had to write the concluding chapter. In other words, 70% of the topics were already done, and while distribution and palaeontology could well have become double chapters, as they are in the <i>Origin</i>, the remaining topics contained no conceptual difficulties to compare with those, such as divergence and instinct that he had already resolved, at least to his own satisfaction. Given the rate that Darwin was working, publication sometime in 1859-1861 was definitely in sight.</p>

<p>But in June 1858, as he noted in his diary, his writing was ‘interrupted’, as is well known, by the arrival of Alfred Russel Wallace’s paper espousing not only evolution, but evolution by an agency that Darwin in his shock saw—accurately or not—as closely akin to natural selection. By July Darwin had regrouped and began writing what he called an abstract of the big book. This new version of the species book would have no footnotes or bibliography, have far less detail, and would be far more readable than <i>Natural Selection</i>. Some nine months later, in March 1859, the abstract was completed and was published on 24 November 1859 as <i>On the Origin of Species, or the preservation of favoured races in the struggle for life</i>. While Darwin carefully preserved many thousands of manuscript pages leading up to the draft of the <i>Origin</i>, and continued to add notes to the <i>Origin</i> portfolios into the 1870s, he seems to have placed little value on preserving the draft itself, and all that survive seem to be mainly those few sheets whose blank sides were used by his children, particularly his son Francis, for drawing paper and those retrieved from the trash basket by others of Darwin’s children, particularly his daughter Henrietta. In total, 45 manuscript pages of the draft, 7 slips with lettered inserts to various pages and 1 fair copy page have been found. Of the 45 full sheets, 26 sheets are part of the Charles Darwin Papers in Cambridge. Most of the latter were distributed as souvenirs by Leonard Darwin acting in consort with his sister Henrietta either to other members of the family or to various scientists and scientific institutions. Leonard in particular gave sheets to fellow supporters of the eugenics movement in Britain and the United States. Ultimately many of the distributed sheets were sold on the open market to collectors and major libraries. Thus the small surviving trove of <i>Origin</i> sheets is the one and only element of the <i>Creation of the Origin</i> collection that isn’t wholly held by Cambridge University Library and Down House.</p>


<p><b>Part II Darwin’s Evidence</b> — the second half and final instalment of Charles Darwin’s Evolution Manuscripts, will be released in June 2015 and constitutes the full, extant documentary record of notes and drafts for the extensive empirical research programme that Darwin undertook in preparing his eight post-<i>Origin</i> books on plants and humans. Darwin used the many experiments and observations he conducted, and the mass of information he compiled from his reading, to establish a well-worked evidentiary framework to support the central theoretical claim of the <i>Origin</i>, namely: that selection has worked in nature to produce evolutionary adaptations. For humans his most focussed empirical study led to <i>Expression of Emotions</i>, which appeared in 1872 and was a compliment to the <i>Descent of Man</i> (1871), which is based on a large compilation of information extracted from the scientific literature. For plants Darwin observed, dissected, and experimented on a wide variety of adaptive phenomena, namely: orchid fertilisation strategies (<i>Orchids</i> 1862, 1877), complex outbreeding mechanisms such as heterostyly and dichogamy (<i>Cross and Self Fertilisation</i>, 1876 and <i>Forms of Flowers</i> 1877), and a series of physiological books (<i>Insectivorous Plants</i>, 1875) and various forms of movement, such as climbing and phototropism (<i>Climbing Plants</i>, 1865, 1875 and <i>Power of Movement</i> 1880).</p>
		
		
		
		

<!-- 
		Want to view items by subject or date? <br /> <a
			href="/search?facet-collection=Darwin Manuscripts">Search the
			Darwin Manuscripts collection</a> <br /> <br />
-->			
	</div>
</div>