package ulcambridge.foundations.viewer.rdf.vocab;

/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from file:/home/kevin/git/gdfeedback-vxtf/src/main/vocabs/content.ttl
 * @author Auto-generated by schemagen on 17 Apr 2015 14:43
 */
public class Content {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2011/content#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Working Draft 29 April 2011";

    /** <p>The Base64 encoded byte sequence of the content.</p> */
    public static final Property bytes = m_model.createProperty( "http://www.w3.org/2011/content#bytes" );

    /** <p>The character encoding used to create a character sequence from a byte sequence
     *  or vice versa.</p>
     */
    public static final Property characterEncoding = m_model.createProperty( "http://www.w3.org/2011/content#characterEncoding" );

    /** <p>The character sequence of the text content.</p> */
    public static final Property chars = m_model.createProperty( "http://www.w3.org/2011/content#chars" );

    /** <p>The character encoding declared in the XML declaration.</p> */
    public static final Property declaredEncoding = m_model.createProperty( "http://www.w3.org/2011/content#declaredEncoding" );

    /** <p>The document type name.</p> */
    public static final Property doctypeName = m_model.createProperty( "http://www.w3.org/2011/content#doctypeName" );

    /** <p>The document type declaration.</p> */
    public static final Property dtDecl = m_model.createProperty( "http://www.w3.org/2011/content#dtDecl" );

    /** <p>The internal document type definition subset within the document type declarations.</p> */
    public static final Property internalSubset = m_model.createProperty( "http://www.w3.org/2011/content#internalSubset" );

    /** <p>The XML content preceding the document type declaration.</p> */
    public static final Property leadingMisc = m_model.createProperty( "http://www.w3.org/2011/content#leadingMisc" );

    /** <p>The document type declarations's public identifier.</p> */
    public static final Property publicId = m_model.createProperty( "http://www.w3.org/2011/content#publicId" );

    /** <p>The XML content following the document type declaration.</p> */
    public static final Property rest = m_model.createProperty( "http://www.w3.org/2011/content#rest" );

    /** <p>The standalone declaration in the XML declaration.</p> */
    public static final Property standalone = m_model.createProperty( "http://www.w3.org/2011/content#standalone" );

    /** <p>The document type declarations's system identifier (typed: xsd:anyURI)</p> */
    public static final Property systemId = m_model.createProperty( "http://www.w3.org/2011/content#systemId" );

    /** <p>The XML version declared in the XML declaration.</p> */
    public static final Property version = m_model.createProperty( "http://www.w3.org/2011/content#version" );

    /** <p>The content.</p> */
    public static final Resource Content = m_model.createResource( "http://www.w3.org/2011/content#Content" );

    /** <p>The base64 encoded content (can be used for binary content).</p> */
    public static final Resource ContentAsBase64 = m_model.createResource( "http://www.w3.org/2011/content#ContentAsBase64" );

    /** <p>The text content (can be used for text content).</p> */
    public static final Resource ContentAsText = m_model.createResource( "http://www.w3.org/2011/content#ContentAsText" );

    /** <p>The XML content (can only be used for XML-wellformed content).</p> */
    public static final Resource ContentAsXML = m_model.createResource( "http://www.w3.org/2011/content#ContentAsXML" );

    /** <p>The document type declaration.</p> */
    public static final Resource DoctypeDecl = m_model.createResource( "http://www.w3.org/2011/content#DoctypeDecl" );

}
