/*
 * File: MyViewport.ui.js
 * Date: Tue Jun 28 2011 18:12:13 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

var store = Ext.create('Ext.data.Store', {
	id : 'simpsonsStore',
	autoLoad : false,
	fields : [ 'name', 'email', 'phone' ],
	pageSize : 1, // items per page
	proxy : {
		type : 'ajax',
		url : 'pagingstore.js', // url that will load data with respect to start
		// and limit params
		reader : {
			type : 'json',
			root : 'items',
			totalProperty : 'total'
		}
	}
});

MyViewportUi = Ext.extend(Ext.Viewport, {
	layout : 'border',
	initComponent : function() {
		this.items = [ {
			xtype : 'container',
			region : 'center',
			width : 100,
			items : [ {
				xtype : 'container',
				el : 'center',
				height : '100%'
			} ]
		}, {
			xtype : 'tabpanel',
			activeTab : 0,
			region : 'east',
			split : true, // enable resizing
			width : '50%',
			title : 'Tools',
			collapsed : false,
			collapsible : true,
			buttonAlign : 'left',
			margins : 0,
			items : [ {
				xtype : 'panel',
				title : 'Transcription',
				el : 'transcription'
			}, {
				xtype : 'panel',
				title : 'Translation'
			}, {
				xtype : 'panel',
				title : 'You might also like...'
			} ]
		}, {
			xtype : 'tabpanel',
			activeTab : 0,
			width : 250,
			height : 250,
			region : 'west',
			collapsed : true,
			collapsible : true,
			title : 'Search',
			items : [ {
				xtype : 'panel',
				title : 'Search'
			}, {
				xtype : 'panel',
				title : 'Advanced'
			}, {
				xtype : 'panel',
				title : 'Bookmarks'
			} ]
		}, {
			xtype : 'container',
			region : 'north',
			el : 'north',
			height : 80
		}, {
			xtype : 'container',
			region : 'south',
			height : 28,
			items : [ {
				xtype : 'toolbar',
				height : 28,
				items : [ 
				'<h1>Extract from Untitled Treatise on Revelation</h1>',
				{
					xtype : 'tbspacer',
					width : 60
				}, // toolbar spacer
				{
					xtype : 'pagingtoolbar',
					store : store,
					width : 250,
					items : []
				},
				'->', // right align spacer
				{
					xtype : 'button',
					text : 'Example Menu',
					menu : {
						xtype : 'menu',
						items : [ {
							xtype : 'menuitem',
							text : 'Report Error'
						}, {
							xtype : 'menuitem',
							text : 'Additional Items'
						} ]
					}
				}, 'Terms & Conditions']
			} ]
		} ];

		MyViewportUi.superclass.initComponent.call(this);
	}
});
